AWSTemplateFormatVersion: 2010-09-09
Description: Template for TN-ITS2 prod cicd

Parameters:
  PipelineName:
    Description: Pipeline name, no capital letter
    Type: String

Resources:

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${PipelineName}-codebuild-role"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action:
              - sts:AssumeRole
      Tags:
        - Key: Name
          Value: !Sub ${PipelineName}-build-role